### ISSUE TITLE
Hanging Note Bug

### ISSUE THREAD

**Issue by Ulfenknulfen** [DLehenbauer/arduino-midi-sound-module#10] opened 2022-08-25 13:20 UTC
Hi !

In most midi files i hear a hanging note thru the whole time.
If i press stop, the hanging note is gone...

Best regards
Paddy

**Comment by Ulfenknulfen** [comment] 2022-09-09 08:46
Hello again.

Is this project not longer supportet?

best regards
Paddy

**Comment by DLehenbauer** [comment] 2022-09-11 01:33
Hi @CometoDiner - This project still seems to be working for me.  I can only think of a few possibilities:

One is that the MIDI file streams events so quickly that it overflows the ring buffer in the Arduino and a keyoff event is lost.  This certainly happens with [Black MIDIs](https://blackmidi.fandom.com/wiki/Home) and is kind of expected.  Black MIDIs will overflow many sound generators from the pre-USB era.

Another is that there is an instrument with an overly long or infinite sustain that is causing the note to be held until an explicit keyoff event, in which case we'll need to identify the offending instrument.

The third is that the files are using something other than keyoff to terminate the note.  (For example, I've seen keyon with a velocity of 0 used.)

If you want to share an example MIDI I can take a look and see if I can spot the problem.  For comparison, [commando.mid](https://www.vgmusic.com/music/computer/commodore/commodore/commando.mid) is an example of a fairly demanding MIDI file that plays correctly for me.

Here is my setup for comparison:
- Windows 10 x64
- [loopMIDI v1.0.16](https://www.tobias-erichsen.de/software/loopmidi.html) to create a virtual loopback device
- [Hairless MIDI v0.4](https://projectgus.github.io/hairless-midiserial/) at bridge to COM4 (don't forget to change baud rate to 38400, run as admin for FTDI devices)
- [Falcosoft Midi Player 6](http://falcosoft.hu/softwares.html#midiplayer) outputting to loopMIDI port.
- Source built today from [a8ad8e3](https://github.com/DLehenbauer/arduino-midi-sound-module/commit/a8ad8e36dbcc8a1c40ec63657f3fc3007a817d10) with [Arduino IDE 1.8.19](https://www.arduino.cc/en/software).

**Comment by Ulfenknulfen** [comment] 2022-09-11 05:46
Hi Daniel !

 

Thanks for quick support.

The attached example files have all issues.

I’m using no usb with your project, i developed an open source Project on vogons.org for the community.

The Beepblaster Module (a Waveblaster compatible Synth.)


 

Thanks for Supporting

 
Paddy

**Comment by DLehenbauer** [comment] 2022-09-12 16:51
Hi @CometoDiner - When replying to emails from GitHub the response is appended to the GitHub issue without preserving file attachments ([here](https://github.com/DLehenbauer/arduino-midi-sound-module/issues/10#issuecomment-1242892473)).

Could you find another way to share some of the MIDI files?  (Perhaps a web link to the originals).

**Comment by Ulfenknulfen** [comment] 2022-09-13 10:59
Hi DLehenbauer,

well, i see - here it is super extreme:
https://legendofmi.com/files/downloads/midis/theme.zip

best regards
Paddy

**Comment by DLehenbauer** [comment] 2022-09-14 00:26
Hi @CometoDiner - There is a sustained E-B-E on channel 4 (Drawbar Organ) at the beginning of the song from ~0:00:04 - 0:00:24.  I can see how that might be mistaken for a hang, but it's actually part of the song.  You'll hear the same with the Microsoft Wavetable GS Synth.

Was that what the issue you were referring to, or was there something different that didn't sound right to you?

**Comment by Ulfenknulfen** [comment] 2022-09-14 07:15
Hi Daniel.

There are many midi files and examples of this error. 
Many Midis also run without problems. It seems to be related to sustain. 
This will not be stopped. Even if you stop the media player, the sustain continues.
This behavior only occurs with the Arduino. All other midi devices run without problems.

I use DOS - Win 98SE, and retro hardware. The beep blaster is connected to the 
wavetable connector on the MPU-401. Other sound cards have been tried without success.

It is a real problem.
best regards
Paddy

**Comment by Ulfenknulfen** [comment] 2022-09-14 08:57
Hi Daniel. Could you check gm1.1 Version from this Paket, please:
https://leejacksonaudio.lbjackson.com/html/download.html

Here is a Video as you can see:
https://youtu.be/PcJ1hsm590E

best regards
Paddy

**Comment by DLehenbauer** [comment] 2022-09-14 23:40
I'm sorry to tell you this, but that MIDI file seems to play correctly as well using the setup I [described earlier](https://github.com/DLehenbauer/arduino-midi-sound-module/issues/10#issuecomment-1242838578).

From your description above, I gather you're using 5-pin MIDI plug to send the data?  If so, did you remember to comment out the '#define' in 'arduino-midi-sound-module.ino' to set the baud rate to 31250?

```cpp
// Defining 'USE_HAIRLESS_MIDI' will set the serial baud rate to 38400.  Comment out the
// below #define to use standard MIDI speed of 31250 baud.
#define USE_HAIRLESS_MIDI       // <-- You should comment this out if using 5-pin MIDI
```

(You'll have to rebuild/reupload the sketch afterward.)

If you've already done this, the next place I would look is the how you are interfacing the Arduino.  Are you using the circuit described in MIDI.h?

```
    Option #3: 5-pin DIN
    --------------------

    You can also build a 5-pin DIN serial MIDI input port for the Arduino and use a standard serial MIDI interface.

    NOTE: Remember to comment-out '#define USE_HAIRLESS_MIDI', per note at top.
    
                220 
        .------^v^v^----------o-------.                      .----o--------------o----< +5v
        |                     |       |                      |    |              |
        |     .-----.         |  1    |      .--------.      |   === 100nF       /
        |    / 5-DIN \       _|_ N    o----1-|        |-6----'    |              \ 
        |   |  (back) |       ^  9    o----2-| H11L1* |-5---------o--< Gnd       / 280
        |   |o       o|      /_\ 1    |      |        |-4----.                   \
        |    \ o o o /        |  4    |      '--------'      |                   /
        |     /-----\         |       |                      |                   |
        |  4 /       \ 5      |       |                      '-------------------o----> RX
        '---'         '-------o-------'
        
    Notes:
        * H11L1 is a PC900 equivalent
```

PS - I would very much like to see your video, but you'll need to make it non-private.

**Comment by Ulfenknulfen** [comment] 2022-09-15 05:15
Hi Daniel.

Now you can watch the Video.
MIDI Signal is already 5V TTL, i don`t use  5pin Midi plug.
Baud rate is also correct.

best regards
Paddy

P.S. My own Midi-Synth (Beepblaster) is working just well with the exact same HW Config.

**Comment by DLehenbauer** [comment] 2022-09-16 14:12
Wow..  that's really close to working.  I wonder if the problem is deterministic.  For example, if you power off/on the Arduino and play the same song, do you always end up with the same notes hanging at the end?

**Comment by Ulfenknulfen** [comment] 2022-09-16 14:28
Hello Daniel :-)

The phenomenon is just as reproducible. I built a switch in the 5V 
line to turn the Arduino off/on. It's the same notes and always the same error. 
The error is always the same with other midi files.

best regards
Paddy

**Comment by Ulfenknulfen** [comment] 2022-09-16 14:31
Is it Easy possible to deactivate sustain support to see if that's the Problem?
I think it may help you.

best regards
Paddy

**Comment by DLehenbauer** [comment] 2022-09-16 15:36
It works the other way around: all instruments are sustained until they receive a MIDI event that tells them to stop playing.

Typically, it's a 'NoteOff' event that releases a note on a channel.  There is also an extended 'AllNotesOff' command that releases all notes on a channel and 'AllSoundOff' that releases the notes and sets the channel volume to zero.

You can also set the note or channel volume to zero without releasing the note.  Technically the note is still playing, but you won't hear it.  The commands that do this are 'SetChannelVolume' (which effects all notes on a channel) or sending a 'NoteOn' event with a velocity of 0.

With my setup, the Arduino is receiving one of the above events, which stops the notes from playing.  It seems that somehow your Arduino is not, which is hard to explain.

Do you have a way to record the MIDI event stream being sent to the Arduino?  Perhaps connect the MIDI-OUT from the MPU-401 to another device and record?

The last thing I can think of to try on my end is to find my old 5-pin MIDI interface and double check that everything still works at 31250 baud.

**Comment by Ulfenknulfen** [comment] 2022-09-16 16:01
Hi Daniel 

Hmmm.
In my beep blaster mode, no notes are held, but switched off immediately after playing. That's probably why I don't have this problem.

 I can rule out the MPU 401 as the cause, since other wavetable cards work without problems on it, 
and the error on the Arduino also occurs when it is connected to other sound cards. 

I've ordered new boards where the TX from the MPU first runs through an optocoupler, 
maybe the signal isn't "clean" enough. 

Let's wait and see what the result is, I'll get back to you - it will take about 2 weeks.

best regards
Paddy

**Comment by DLehenbauer** [comment] 2022-09-16 23:49
I was thinking it might be a signal integrity issue also until you mentioned it was deterministic.  Now I'm wondering if the sound card or the media player is changing the MIDI event stream.  For example, perhaps the MIDI file uses some extension that the older player/card misinterprets, causing a few events to be dropped.  

Do you have a schematic for your board?  (You can paste images into GitHub issues).  Are you perhaps not using an Arduino Uno, but instead have an Atmel 328p directly on the board?

**Comment by Ulfenknulfen** [comment] 2022-09-17 07:09
Hi Daniel!

I don't think the midiplayer changes the stream. Then other Midi devices would also be affected. 
I attached the schematic, and yes, the 328p is right on the board.

best regards
Paddy

**Comment by Ulfenknulfen** [comment] 2022-09-24 16:37
Hi Daniel.

Same problem with optocoupler version. It must be an software issue.

best regards
Paddy

**Comment by DLehenbauer** [comment] 2022-10-01 01:01
Yeah, since you say the problem is deterministic, I wasn't too hopeful that it was a signal integrity issue, but thank you for trying it.

I can only think of a few ways in which you and I could get different results:
1.  We're running different firmware on the 328P.
2.  A difference in hardware.
3.  A difference in the bitstream sent to RX (the blue wire in the photo).

The first could happen if you checkout out a different commit, or if the version of the Arduino IDE your using bundles a different GCC or uses different compiler options.  (I think unlikely, but it's possible.)

Regarding a hardware difference, your schematic looks right to me, and I've successfully run this project in the past with a 328P on a breadboard.  The one idea I had is if your crystal frequency isn't 16.0 MHz, in which case you'll need to adjust F_CPU or the USART baud rate will be wrong (see midi.h).

Regarding a difference in bitstream, there is a lot of different software and hardware between the contents of the MIDI file and the RX pin of the 328P.  It may be that something in that chain of media player, driver, and hardware is altering the stream in a way the firmware doesn't handle well.

I tried switching to a 5-pin MIDI interface, which makes my setup a closer to yours:
* 31250 baud via H11L1
* No longer need Hairless MIDI and loopMIDI software
* Arduino's built-in USB to serial bridge hardware bypassed
* SPI OLED display removed
* USB is only providing +5v power

Here is the full description of my setup:
- Windows 10 x64
- [Falcosoft Midi Player 6](http://falcosoft.hu/softwares.html#midiplayer) (also tried [TMIDI](https://grandgent.com/tom/projects/tmidi/))
- [MIDIPlus TBOX 2x2](http://www.midiplus.com/html/tbox.html) with Microsoft's generic driver.
- 5-pin MIDI to RX interface as described in [midi.h](https://github.com/DLehenbauer/arduino-midi-sound-module/blob/master/arduino-midi-sound-module/midi.h)
- Undefine USE_HAIRLESS_MIDI in [arduino-midi-sound-module.ino](https://github.com/DLehenbauer/arduino-midi-sound-module/blob/master/arduino-midi-sound-module/arduino-midi-sound-module.ino) to use 31250 baud
- Source built from [a8ad8e3](https://github.com/DLehenbauer/arduino-midi-sound-module/commit/a8ad8e36dbcc8a1c40ec63657f3fc3007a817d10) with [Arduino IDE 1.8.19](https://www.arduino.cc/en/software).

Here's a photo:

![PXL_20220930_211249646](https://user-images.githubusercontent.com/11368662/193358442-936f49d0-425e-453b-827e-0161bb1fcab7.jpg)

Unfortunately, the song still plays correctly for me.

I'll keep thinking about it, but at this point my suggestion would be to try to divide and conquer.  If you can, build the working configuration using a modern PC, generic MIDI interface, and a standard Uno like I have in the photo above.  Then try substituting your Waveblaster board.  If your waveblaster board works with the modern software/hardware, we know it's the third issue: something is modifying the bitstream.  If the problem replicates with your board, then we know it's different firmware or a subtle hardware difference.

**Comment by Ulfenknulfen** [comment] 2022-10-22 16:06
Hi Daniel.

The Problem is solved. I used all the time the MPU401 Driver from Microsoft (in Win98SE).
With this driveryou have this issues all the time.
But when i use the original Roland MPU401 Driver for the NON-PNP Card.
the issue is gone.

It was a Driver Problem ;-)

best regards and thanks so much for your Support

Paddy

**Comment by DLehenbauer** [comment] 2022-10-24 16:46
Whew!  Glad you were able to figure it out!

Thanks for letting me know.  I'll go ahead and close this issue.

**Closed as completed by DLehenbauer** 2022-10-24 16:46 UTC
